export type ContactTag = "VIP" | "Lead Quente" | "Cliente" | "Inativo" | (string & {});
export type ContactOrigin = "manual" | "csv" | "bot" | "form";
export type LastInteractionBucket = "today" | "week" | "month" | "30plus" | "all";

export type ContactRow = {
  id: string;
  name: string;
  initials: string;
  phone: string;
  email: string;
  tags: ContactTag[];
  favorite: boolean;
  lastMessage: string;
  lastInteractionText: string; // ex: "5 min atrás"
  lastInteractionBucket: Exclude<LastInteractionBucket, "all">;
  origin: ContactOrigin;
  company?: string;
  cpfCnpj?: string;
  birthDate?: string; // ISO date (YYYY-MM-DD)
  address?: string;
  notes?: string;
};

export const CONTACTS_COUNTS_MOCK = {
  total: 156,
  favorites: 12,
  untagged: 23,
  new7d: 12,
  activeLeads: 34,
  vips: 8,
} as const;

const makeInitials = (fullName: string) => {
  const parts = fullName.trim().split(/\s+/).slice(0, 2);
  return parts
    .map((p) => p[0] ?? "")
    .join("")
    .toUpperCase();
};

export const CONTACTS_MOCK: ContactRow[] = [
  {
    id: "ct-1",
    name: "João da Silva",
    initials: makeInitials("João da Silva"),
    phone: "(11) 98765-4321",
    email: "joao.silva@gmail.com",
    tags: ["VIP", "Cliente"],
    favorite: true,
    lastMessage: "Obrigado pelo atendimento!",
    lastInteractionText: "5 min atrás",
    lastInteractionBucket: "today",
    origin: "manual",
    company: "Silva & Filhos",
  },
  {
    id: "ct-2",
    name: "Maria Oliveira",
    initials: makeInitials("Maria Oliveira"),
    phone: "(21) 99876-5432",
    email: "maria.oliveira@hotmail.com",
    tags: ["Lead Quente"],
    favorite: false,
    lastMessage: "Gostaria de agendar uma consulta",
    lastInteractionText: "1 hora atrás",
    lastInteractionBucket: "today",
    origin: "form",
    company: "Clínica Vida",
  },
  {
    id: "ct-3",
    name: "Carlos Santos",
    initials: makeInitials("Carlos Santos"),
    phone: "(31) 99123-4567",
    email: "carlos.santos@gmail.com",
    tags: ["Cliente"],
    favorite: false,
    lastMessage: "Pode me enviar os detalhes do plano?",
    lastInteractionText: "2 dias atrás",
    lastInteractionBucket: "week",
    origin: "bot",
    company: "Santos Imóveis",
  },
  {
    id: "ct-4",
    name: "Ana Costa",
    initials: makeInitials("Ana Costa"),
    phone: "(41) 99654-3210",
    email: "ana.costa@outlook.com",
    tags: ["VIP"],
    favorite: true,
    lastMessage: "Perfeito, vou fazer o Pix agora.",
    lastInteractionText: "3 dias atrás",
    lastInteractionBucket: "week",
    origin: "manual",
    company: "Costa Beauty",
  },
  {
    id: "ct-5",
    name: "Pedro Almeida",
    initials: makeInitials("Pedro Almeida"),
    phone: "(51) 98888-7777",
    email: "pedro.almeida@gmail.com",
    tags: [],
    favorite: false,
    lastMessage: "Tem como remarcar para sexta?",
    lastInteractionText: "6 dias atrás",
    lastInteractionBucket: "week",
    origin: "csv",
    company: "Almeida Fitness",
  },
  {
    id: "ct-6",
    name: "Juliana Lima",
    initials: makeInitials("Juliana Lima"),
    phone: "(61) 99777-2222",
    email: "juliana.lima@yahoo.com",
    tags: ["Lead Quente"],
    favorite: false,
    lastMessage: "Qual o valor para iniciar hoje?",
    lastInteractionText: "8 dias atrás",
    lastInteractionBucket: "month",
    origin: "form",
    company: "Lima Consultoria",
  },
  {
    id: "ct-7",
    name: "Rafael Souza",
    initials: makeInitials("Rafael Souza"),
    phone: "(71) 99999-0000",
    email: "rafa.souza@gmail.com",
    tags: ["Cliente"],
    favorite: false,
    lastMessage: "Consegue emitir nota fiscal?",
    lastInteractionText: "12 dias atrás",
    lastInteractionBucket: "month",
    origin: "manual",
    company: "Souza Imports",
  },
  {
    id: "ct-8",
    name: "Camila Rocha",
    initials: makeInitials("Camila Rocha"),
    phone: "(81) 98812-3456",
    email: "camila.rocha@hotmail.com",
    tags: ["Inativo"],
    favorite: false,
    lastMessage: "Vou pensar e volto a falar.",
    lastInteractionText: "35 dias atrás",
    lastInteractionBucket: "30plus",
    origin: "csv",
    company: "Rocha Store",
  },
  {
    id: "ct-9",
    name: "Lucas Ferreira",
    initials: makeInitials("Lucas Ferreira"),
    phone: "(19) 99222-3344",
    email: "lucas.ferreira@gmail.com",
    tags: ["Cliente"],
    favorite: true,
    lastMessage: "Pode confirmar o horário?",
    lastInteractionText: "3 horas atrás",
    lastInteractionBucket: "today",
    origin: "bot",
    company: "Ferreira Serviços",
  },
  {
    id: "ct-10",
    name: "Fernanda Martins",
    initials: makeInitials("Fernanda Martins"),
    phone: "(85) 99765-4321",
    email: "fernanda.martins@gmail.com",
    tags: ["VIP", "Cliente"],
    favorite: false,
    lastMessage: "Adorei o atendimento, obrigada!",
    lastInteractionText: "Ontem",
    lastInteractionBucket: "week",
    origin: "manual",
    company: "Martins Studio",
  },
  {
    id: "ct-11",
    name: "Bruno Carvalho",
    initials: makeInitials("Bruno Carvalho"),
    phone: "(27) 98876-1111",
    email: "bruno.carvalho@outlook.com",
    tags: ["Lead Quente"],
    favorite: false,
    lastMessage: "Quais são as formas de pagamento?",
    lastInteractionText: "2 horas atrás",
    lastInteractionBucket: "today",
    origin: "form",
    company: "Carvalho Tech",
  },
  {
    id: "ct-12",
    name: "Patrícia Nogueira",
    initials: makeInitials("Patrícia Nogueira"),
    phone: "(48) 99712-0001",
    email: "patricia.nogueira@gmail.com",
    tags: [],
    favorite: false,
    lastMessage: "Consigo integrar com Google Sheets?",
    lastInteractionText: "4 dias atrás",
    lastInteractionBucket: "week",
    origin: "bot",
    company: "Nogueira Academy",
  },
  {
    id: "ct-13",
    name: "Gustavo Ribeiro",
    initials: makeInitials("Gustavo Ribeiro"),
    phone: "(62) 99111-2222",
    email: "gustavo.ribeiro@gmail.com",
    tags: ["Cliente"],
    favorite: false,
    lastMessage: "Pode me mandar o contrato?",
    lastInteractionText: "10 dias atrás",
    lastInteractionBucket: "month",
    origin: "csv",
    company: "Ribeiro & Co.",
  },
  {
    id: "ct-14",
    name: "Camila Barros",
    initials: makeInitials("Camila Barros"),
    phone: "(11) 90000-1111",
    email: "camila.barros@gmail.com",
    tags: ["VIP"],
    favorite: true,
    lastMessage: "Fechado! Pode agendar para sábado.",
    lastInteractionText: "3 dias atrás",
    lastInteractionBucket: "week",
    origin: "manual",
    company: "Barros Imobiliária",
  },
  {
    id: "ct-15",
    name: "Diego Freitas",
    initials: makeInitials("Diego Freitas"),
    phone: "(24) 99800-7700",
    email: "diego.freitas@hotmail.com",
    tags: ["Inativo"],
    favorite: false,
    lastMessage: "No momento não vou conseguir.",
    lastInteractionText: "40 dias atrás",
    lastInteractionBucket: "30plus",
    origin: "csv",
    company: "Freitas Auto",
  },
  {
    id: "ct-16",
    name: "Larissa Menezes",
    initials: makeInitials("Larissa Menezes"),
    phone: "(13) 99777-7777",
    email: "larissa.menezes@gmail.com",
    tags: ["Lead Quente"],
    favorite: false,
    lastMessage: "Tem desconto no plano anual?",
    lastInteractionText: "6 horas atrás",
    lastInteractionBucket: "today",
    origin: "bot",
    company: "Menezes Store",
  },
  {
    id: "ct-17",
    name: "Renata Dias",
    initials: makeInitials("Renata Dias"),
    phone: "(79) 99123-9876",
    email: "renata.dias@yahoo.com",
    tags: ["Cliente"],
    favorite: false,
    lastMessage: "Pode enviar o link de pagamento?",
    lastInteractionText: "2 dias atrás",
    lastInteractionBucket: "week",
    origin: "manual",
    company: "Dias & Cia",
  },
  {
    id: "ct-18",
    name: "Thiago Pires",
    initials: makeInitials("Thiago Pires"),
    phone: "(47) 98888-0009",
    email: "thiago.pires@outlook.com",
    tags: [],
    favorite: false,
    lastMessage: "Como funciona o ZapFllow de lembrete?",
    lastInteractionText: "9 dias atrás",
    lastInteractionBucket: "month",
    origin: "form",
    company: "Pires Consult",
  },
  {
    id: "ct-19",
    name: "Aline Vieira",
    initials: makeInitials("Aline Vieira"),
    phone: "(22) 99700-1234",
    email: "aline.vieira@gmail.com",
    tags: ["Cliente"],
    favorite: false,
    lastMessage: "Me avise quando estiver pronto.",
    lastInteractionText: "14 dias atrás",
    lastInteractionBucket: "month",
    origin: "manual",
    company: "Vieira Foods",
  },
  {
    id: "ct-20",
    name: "Eduardo Farias",
    initials: makeInitials("Eduardo Farias"),
    phone: "(91) 98989-1212",
    email: "eduardo.farias@gmail.com",
    tags: ["VIP", "Cliente"],
    favorite: false,
    lastMessage: "Ótimo! Obrigado.",
    lastInteractionText: "30 min atrás",
    lastInteractionBucket: "today",
    origin: "manual",
    company: "Farias Comércio",
  },
];
