// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvcanphpifzocejtqdip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2Y2FucGhwaWZ6b2NlanRxZGlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0ODUwMTIsImV4cCI6MjA4NTA2MTAxMn0.4rgWVGicjxB55H4HFrHSQRVrxORkirFsB2HR9lOHYZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});