import type { ConversationListItem, ConversationThread } from "@/pages/dashboard/conversas/types";

export const conversationsMock: ConversationListItem[] = [
  {
    id: "c1",
    name: "João Silva",
    lastMessage: "Gostaria de agendar uma cons...",
    lastMessageAtLabel: "5 min atrás",
    unreadCount: 3,
    online: true,
    assignedTo: "Eu",
    tags: ["VIP"],
    statusLabel: "Aberto",
    pinned: true,
  },
  {
    id: "c2",
    name: "Maria Oliveira",
    lastMessage: "Obrigada pelo atendimento!",
    lastMessageAtLabel: "1 hora atrás",
    unreadCount: 0,
    online: false,
    assignedTo: "Maria Santos",
    tags: [],
    statusLabel: "Resolvido",
  },
  {
    id: "c3",
    name: "Carlos Santos",
    lastMessage: "Você: Enviamos o link por email",
    lastMessageAtLabel: "Ontem",
    unreadCount: 2,
    online: true,
    assignedTo: "João Silva",
    tags: ["Suporte"],
    statusLabel: "Aberto",
  },
  {
    id: "c4",
    name: "Ana Paula",
    lastMessage: "Quero saber o status do meu pedido",
    lastMessageAtLabel: "Agora",
    unreadCount: 1,
    online: true,
    assignedTo: null,
    tags: ["Urgente"],
    statusLabel: "Aberto",
  },
  {
    id: "c5",
    name: "Fernanda Lima",
    lastMessage: "Perfeito, obrigado!",
    lastMessageAtLabel: "2 min",
    unreadCount: 0,
    online: false,
    assignedTo: "Eu",
    tags: ["Vendas"],
    statusLabel: "Aberto",
  },
  {
    id: "c6",
    name: "Rafael Souza",
    lastMessage: "Pode me passar os valores?",
    lastMessageAtLabel: "1h",
    unreadCount: 0,
    online: true,
    assignedTo: "Eu",
    tags: ["Vendas"],
    statusLabel: "Aberto",
  },
  {
    id: "c7",
    name: "Beatriz Rocha",
    lastMessage: "Não consegui acessar minha conta",
    lastMessageAtLabel: "Ontem",
    unreadCount: 4,
    online: false,
    assignedTo: "João Silva",
    tags: ["Suporte"],
    statusLabel: "Aberto",
  },
  {
    id: "c8",
    name: "Pedro Henrique",
    lastMessage: "Já paguei, falta confirmar",
    lastMessageAtLabel: "Segunda",
    unreadCount: 0,
    online: false,
    assignedTo: "Maria Santos",
    tags: ["VIP"],
    statusLabel: "Resolvido",
  },
  {
    id: "c9",
    name: "Juliana Mendes",
    lastMessage: "Ok! Vou aguardar.",
    lastMessageAtLabel: "15/01",
    unreadCount: 0,
    online: false,
    assignedTo: null,
    tags: [],
    statusLabel: "Resolvido",
  },
  {
    id: "c10",
    name: "Luiz Fernando",
    lastMessage: "Tem como reagendar para amanhã?",
    lastMessageAtLabel: "Ontem",
    unreadCount: 1,
    online: true,
    assignedTo: "Eu",
    tags: ["VIP"],
    statusLabel: "Aberto",
  },
  // (mock extra) até 45
  ...Array.from({ length: 35 }).map((_, i) => {
    const n = i + 11;
    const ts = ["Agora", "2 min", "1h", "Ontem", "Segunda", "15/01"][i % 6];
    const tags = ([[], ["VIP"], ["Suporte"], ["Vendas"], ["Urgente"]] as const)[i % 5];
    return {
      id: `c${n}`,
      name: `Contato ${n}`,
      lastMessage: [
        "Pode me ajudar com isso?",
        "Você: Obrigado!",
        "Enviei os dados no email.",
        "Quero falar com atendente.",
        "Qual o horário de funcionamento?",
      ][i % 5],
      lastMessageAtLabel: ts,
      unreadCount: i % 7 === 0 ? 1 + (i % 3) : 0,
      online: i % 4 !== 0,
      assignedTo: (i % 3 === 0 ? "Eu" : i % 3 === 1 ? "João Silva" : "Maria Santos") as any,
      tags: [...tags] as any,
      statusLabel: (i % 4 === 0 ? "Resolvido" : "Aberto") as "Resolvido" | "Aberto",
      pinned: i % 13 === 0,
    };
  }),
];

export const threadJoaoSilva: ConversationThread = {
  id: "c1",
  contactName: "João Silva",
  contactOnline: true,
  tags: ["VIP", "Cliente"],
  lastSeenLabel: "Visto por último hoje às 14:32",
  messages: [
    { id: "m1", kind: "system", time: "", dateLabel: "Hoje", text: "Hoje" },
    {
      id: "m2",
      kind: "in",
      authorLabel: "João",
      time: "14:25",
      text: "Olá! Gostaria de informações sobre agendamento",
    },
    {
      id: "m3",
      kind: "out",
      authorLabel: "Bot",
      time: "14:26",
      bot: true,
      delivery: "read",
      text:
        "Olá João! 😊 Estou aqui para ajudar. Você gostaria de:\n1️⃣ Agendar nova consulta\n2️⃣ Remarcar consulta existente\n3️⃣ Falar com atendente",
    },
    { id: "m4", kind: "in", authorLabel: "João", time: "14:27", text: "3" },
    { id: "m5", kind: "system", time: "", text: "👤 Você assumiu a conversa" },
    { id: "m6", kind: "out", authorLabel: "Você", time: "14:28", delivery: "read", text: "Olá João! Sou a Maria, em que posso ajudar?" },
    { id: "m7", kind: "in", authorLabel: "João", time: "14:30", text: "Preciso remarcar minha consulta de amanhã" },
    { id: "m8", kind: "out", authorLabel: "Você", time: "14:31", delivery: "read", text: "Sem problemas! Qual seria a melhor data para você?" },
    { id: "m9", kind: "in", authorLabel: "João", time: "14:32", text: "Sexta-feira de manhã se possível" },
    {
      id: "m10",
      kind: "out",
      authorLabel: "Você",
      time: "14:35",
      delivery: "delivered",
      text: "Perfeito! Temos disponibilidade na sexta às 10h. Confirmo?",
    },
    { id: "m11", kind: "in", authorLabel: "João", time: "14:36", text: "Sim, confirmo! 👍" },
    {
      id: "m12",
      kind: "out",
      authorLabel: "Você",
      time: "14:37",
      delivery: "delivered",
      text:
        "✅ Consulta reagendada para sexta-feira, 31/01, às 10h.\nVocê receberá um lembrete 1 dia antes.\nMais alguma dúvida?",
    },
    { id: "m13", kind: "in", authorLabel: "João", time: "14:38", text: "Não, muito obrigado!" },
    { id: "m14", kind: "out", authorLabel: "Você", time: "14:39", delivery: "sent", text: "Por nada! Até sexta! 😊" },
    { id: "m15", kind: "system", time: "", text: "Conversa marcada como resolvida" },
  ],
};

export const quickRepliesMock = [
  { id: "qr1", title: "Saudação Inicial", text: "Olá! Como posso ajudar?" },
  { id: "qr2", title: "Horário de Funcionamento", text: "Atendemos de seg-sex, 8h-18h" },
  { id: "qr3", title: "Dados para Pagamento", text: "Pix: chave@email.com" },
];
